### ISSUE TITLE
Install on Win 7

### ISSUE THREAD

**Issue by Djef32** [vanlooverenkoen/MIDIMACRO#1]
Hello Koen, 
I'm Jf Denis from Gembloux, musican by motivation on Win 7 x64, cubase 5, M50 Korg , silver flute, guitare and piano, and I'm really interrested by your midimacro project which will help to be more creative :)

I tried this morning to install the soft on both my  tablet asus android 4.4 and my pc  Win7 but when installing the source MIDIMACRO Installer 2.2.0 I get an error message 

Maybe it's not design to work with win 7 and only with 8.1 , 10 because of extra features in these version ?. The first message was a signature issue, so I 

Do I have a chance to run the Midimacro server on my win 7 ? 

here is the log : 

An unexpected application exception occurred

  Exception 

System.NullReferenceException: Object reference not set to an instance of an object.
   at View.MidiMacroApplication.OnStartup(StartupEventArgs e) in C:\GitHub\MIDIMACRO NEW\MIDIMACRO WIN\View\MidiMacroApplication.xaml.cs:line 64
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 Stacktrace 

    at View.MidiMacroApplication.OnStartup(StartupEventArgs e) in C:\GitHub\MIDIMACRO NEW\MIDIMACRO WIN\View\MidiMacroApplication.xaml.cs:line 64
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 Message 
 Object reference not set to an instance of an object.
 INNEREXCEPTION Message
 INNEREXCEPTION Stacktrace

Hope receiving some news from you 
Good continuation and kind regards
Jean-François Denis
tel 0478 84 97 99
Gembloux
IT support 1st line for BNPP and musician by passion

**Comment by vanlooverenkoen** [comment]
Hi,
Happy to hear you found my project and you would like to use it.  I made this project for school. So compatibility wise it only had to work on my pc. So I only tested it for Windows 10. I currently don't own a Windows 7 operating system. 

I see you are using 2.2.0 as listed in on my ([MIDIMACRO website](http://vanlooverenkoen.be/MIDIMACRO)). Now it seems I forgot to update the download on the website. please check back [here](http://vanlooverenkoen.be/MIDIMACRO/#download) to download the latest version 2.3.0. If you are experiencing the same issue I will buy myself Windows 7 and I will try to fix the issue as fast as I can (please resend the error codes you are getting if you are experiencing the same issue).

Thank you very much for contacting me with this issue.
By the 12 of april I will probably also release another version of the android app so he can go public instead of Beta.

Sincerly yours and happy coding,
Koen Van Looveren

**Comment by Djef32** [comment]
Hello Koen, 
Thank you for your friendly answer. i must to say after little investigation that the native Midi over Wifi of Windows 10 is not present on Win 7.. A workaround is using Apple Bonjour which install this features.. after that , the RtpServer is available for midi over Wifi. see the research of http://www.tobias-erichsen.de/software/rtpmidi.html who is talking about..
I first tried with the tool RtpMidi v1.1.8 which allowed me to use "Touch DAW" on android ( Humatic software). the responsness is quick - 3millisec. - but the android app is not customizable and cubase 5 answer correctly for the main task but iteratively for other task like the remotly access to a VST instrument (like groove agent one for example). i was looking for something more customizable like your soft :)

.. I know also that the core of Win 10 is different than the core of Win 7x64 , perhaps meaning that some media features are completly not available for win 7 ? 

I tried the build 2.3 but receive the same error message which I post here below

An unexpected application exception occurred


  Exception 
System.NullReferenceException: Object reference not set to an instance of an object.
   at View.MidiMacroApplication.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 Stacktrace 
    at View.MidiMacroApplication.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 Message  Object reference not set to an instance of an object.

 INNEREXCEPTION Message
 INNEREXCEPTION Stacktrace

.. if you want from me to do more test , I will do with pleasure because it's a great challenge : new midi norm which was not changed since midi message through DIN plug in the year 1988 :)
I believe in your project but don't spent too much time for win 7 because the futur is well Win 10.
Now I must admit that it exists a big community of Cubase 5 users with Win 7 and that a good tool is most than the welcome. 

Thanks for all dear and I will read you with pleasure
Kind regards
Jf

**Comment by vanlooverenkoen** [comment]
Hello Jean-François,

I'm sorry you are still having the same issue. When I have some time available I will try to fix this issue. Indeed I have no idea if it is even possible. But if I don't try we both will never know if it could work for your system. I love challanges ;-) 

In the meantime I rewrote my [README.md file](https://github.com/vanlooverenkoen/MIDIMACRO/blob/master/README.md). It now contains more information what this project is about.

I will get back to you as soon as I can. And thank you very much for supporting me on this journey.

Kind regards
Koen Van Looveren

**Comment by Djef32** [comment]
Hello Koen, this is spring time, keep one day to breath :) and enjoy the sun !
I first will deeply check your readme advice and will try to be more consequent in the detail of my observations. 
Also, if you want, you may use teamviewer 11 remotely, with my pc to go deeper in the analyse , so you will run MidiMacro on Win 7 + Cubase 5 if you want : we can arrange an afternoon from 18:00 for example.. let me know.
Kr, 
Jf

**Comment by vanlooverenkoen** [comment]
Hi,

Thank you, I already bought Windows 7 for testing & developing the new update (Windows 7). But it is good to know you want to participate. As I said I am a student. This is my final year and next week I have my exams. So it will probably be for the week of the 27th of March.

Kind regards
Koen Van Looveren

**Comment by Djef32** [comment]
School firts ! I understand :) ..., for holidays is also good, I follow you !

**Comment by vanlooverenkoen** [comment]
I finished my examens yesterday. And I think I got good news for you. I just fixed a bug for windows 7 and I got it running on Windows 7 Pro 64-bit. You can download the the latest update at [my website.](http://vanlooverenkoen.be/MIDIMACRO/#download) If you still have problems with the installation, please let me know ;)

**Comment by Djef32** [comment]
Hello Koen, Little feedback : I downloaded the version 2.3.0 which it's seems the same version as previous and  when reinstall it and running it as admin, I received the same message.
-->  I suspect this is linked to a missing library on my side.
I have the my last install visual c++ 2015  redistribuable x64.. ?
Kind regards
Jf

**Comment by vanlooverenkoen** [comment]
Hi, offcourse I didn't change the html to version 2.4.0. please try again. I'm sorry ;)

**Comment by Djef32** [comment]
to fast :-) what a man !

**Comment by Djef32** [comment]
It's well started ! now I will play with it !

**Comment by Djef32** [comment]
Hello Koen, I think I need your help to configure Midimacro with the cubase 5.1 : 
When I connect Midi OX to see the midi data's, It doesn't show Midiserver but well Touch OSC Bridge that I had installed previously. 

When opening Touch Osc Bridge, Then Midimacro , Then selecting Touch OSC as Midi Device (in Midi OX : , It is showned in Midi Ox, and data's are dropped as below
Timstamp  IN Port Status data1 data2 channel  note event
0003CE20   8  12     B0     02    1B      1             ---  CC: Breath
0003CE39   8  12     B0    02    1C    1  ---  CC: Breath
0003CF8D   8  12     B0    02    11    1  ---  CC: Breath
...

But when I go in QB5, adding generic control as device, selecting TOUCH OSC as Midi input,  I see no Midi activities from MIDIMACRO on my asus Tablet. I need to say : the ip adresse is correct, the flow is well authorized through the firewall and I see midi messages on MidiOx Control screen.
I'm surely missing an important step.. Any help is greatly appreciate :)

**Comment by vanlooverenkoen** [comment]
Please Create a new Issue. If at a later time other people have the same issue they can easily find this issue.

**Comment by Djef32** [comment]
.. will do ! cheers
