### ISSUE TITLE
Cubase 5 & MidiMacro

### ISSUE THREAD

**Issue by Djef32** [vanlooverenkoen/MIDIMACRO#2]
Hello Koen, I think I need your help to configure Midimacro with the cubase 5.1 :
How can I show MidiMacro as Midi device within this old cubase 5 stuff ? 

Test operation :
When I connect Midi OX to see the midi data's from Midi Device,  It doesn't show Midi Macro Server
It doesn't show MidiMacroServer but well Touch OSC Bridge that I had installed previously.
So I have no other choice but use Touch OSc Bridge in Midi Ox and Touch OSc Bridge in Midi Macro Server.

When selecting 'Touch Osc Bridge' as midi device in 'Midi Ox', Doing the same in 'Midimacro' , Then selecting Touch OSC as midi device 
there is an activity and data's are dropped in Midi Ox as below
Timestamp IN Port Status data1 data2 channel note event
0003CE20 8 12 B0 02 1B 1 --- CC: Breath
0003CE39 8 12 B0 02 1C 1 --- CC: Breath
0003CF8D 8 12 B0 02 11 1 --- CC: Breath
...

But when I go in QB5, adding generic control as device, selecting TOUCH OSC as Midi device input, 
I see no Midi activities at allt. ( using my tablet asus and Midi Macro on in through my wifi) 
I need to say : the ip adresse is correct, the flow is well authorized through the firewall and I see midi messages on MidiOx Control screen.
I'm surely missing an important step.. 
Any help is greatly appreciate :)

Kr, 
Jf

**Comment by vanlooverenkoen** [comment]
Hi,

This is normal. The midimacro server will be used for communication with the MIDIMACRO program over tcp. For only internal use. (At this point it only supports changing your windows mixer volume channels)

Koen
